# Generated by Django 4.2.9 on 2025-06-17 10:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход'), ('debt', 'Долг')], max_length=10, verbose_name='Тип категории')),
                ('is_default', models.BooleanField(default=False, verbose_name='Категория по умолчанию')),
                ('user', models.ForeignKey(blank=True, help_text='Если null - системная категория для всех пользователей', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('type', 'name'),
                'indexes': [models.Index(fields=['user', 'type'], name='categories__user_id_135dec_idx'), models.Index(fields=['is_default'], name='categories__is_defa_313f6b_idx')],
                'unique_together': {('user', 'name', 'type')},
            },
        ),
    ]
