# Generated by Django 4.2.9 on 2025-06-17 12:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0002_goaltransaction_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название события')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('reminder_type', models.CharField(choices=[('payment', 'Платеж'), ('debt', 'Долг'), ('goal', 'Цель'), ('custom', 'Произвольное')], default='custom', max_length=10, verbose_name='Тип напоминания')),
                ('scheduled_time', models.DateTimeField(verbose_name='Время срабатывания')),
                ('repeat', models.CharField(choices=[('once', 'Однократно'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='once', max_length=10, verbose_name='Периодичность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма (для платежей/долгов)')),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='Последняя отправка')),
                ('next_reminder', models.DateTimeField(blank=True, null=True, verbose_name='Следующее напоминание')),
                ('telegram_notified', models.BooleanField(default=False, verbose_name='Telegram уведомление отправлено')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='goals.goal', verbose_name='Связанная цель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='users.user')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReminderHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время отправки')),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('failed', 'Ошибка отправки'), ('manual', 'Отправлено вручную')], default='sent', max_length=20, verbose_name='Статус отправки')),
                ('telegram_message_id', models.IntegerField(blank=True, null=True, verbose_name='ID сообщения в Telegram')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reminders.reminder', verbose_name='Напоминание')),
            ],
            options={
                'verbose_name': 'История напоминания',
                'verbose_name_plural': 'История напоминаний',
                'ordering': ('-sent_at',),
                'indexes': [models.Index(fields=['reminder', 'sent_at'], name='reminders_r_reminde_a874f4_idx'), models.Index(fields=['status'], name='reminders_r_status_43ee2a_idx'), models.Index(fields=['sent_at'], name='reminders_r_sent_at_160009_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['user', 'is_active'], name='reminders_r_user_id_898b13_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['scheduled_time', 'is_active'], name='reminders_r_schedul_f13cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['next_reminder', 'is_active'], name='reminders_r_next_re_f6c29c_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['reminder_type'], name='reminders_r_reminde_c61630_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['repeat'], name='reminders_r_repeat_6eb386_idx'),
        ),
    ]
