# Generated by Django 4.2.9 on 2025-06-17 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Например: telegram, instagram, google, referral, direct', max_length=100, unique=True, verbose_name='Название источника')),
                ('description', models.TextField(blank=True, verbose_name='Описание источника')),
                ('utm_source', models.CharField(blank=True, max_length=100, verbose_name='UTM источник')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='UTM медиум')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='UTM кампания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Источник трафика',
                'verbose_name_plural': 'Источники трафика',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['name'], name='sources_sou_name_d7c3f4_idx'), models.Index(fields=['is_active'], name='sources_sou_is_acti_01a13f_idx')],
            },
        ),
    ]
