# Generated by Django 4.2.9 on 2025-06-17 10:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCommandLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Распознанный текст')),
                ('original_audio_duration', models.FloatField(blank=True, null=True, verbose_name='Длительность аудио (сек)')),
                ('command_type', models.CharField(choices=[('expense', 'Расход'), ('income', 'Доход'), ('goal', 'Цель'), ('debt', 'Долг'), ('query', 'Запрос'), ('unknown', 'Неизвестно')], default='unknown', max_length=10, verbose_name='Тип команды')),
                ('status', models.CharField(choices=[('processing', 'Обрабатывается'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('partial', 'Частично выполнено')], default='processing', max_length=10, verbose_name='Статус обработки')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='Уверенность распознавания (0-1)')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='Время обработки (сек)')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('extracted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Извлеченная сумма')),
                ('extracted_currency', models.CharField(blank=True, max_length=3, verbose_name='Извлеченная валюта')),
                ('created_transaction_id', models.UUIDField(blank=True, null=True, verbose_name='ID созданной транзакции')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время получения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_commands', to='users.user')),
            ],
            options={
                'verbose_name': 'Лог голосовой команды',
                'verbose_name_plural': 'Логи голосовых команд',
                'ordering': ('-received_at',),
                'indexes': [models.Index(fields=['user', 'command_type'], name='bot_voiceco_user_id_1d5b03_idx'), models.Index(fields=['status'], name='bot_voiceco_status_bae093_idx'), models.Index(fields=['received_at'], name='bot_voiceco_receive_49ab4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='BotSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_chat_id', models.BigIntegerField(verbose_name='ID чата в Telegram')),
                ('session_type', models.CharField(choices=[('voice', 'Голосовая'), ('text', 'Текстовая'), ('mixed', 'Смешанная')], default='mixed', max_length=10, verbose_name='Тип сессии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало сессии')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец сессии')),
                ('messages_count', models.PositiveIntegerField(default=0, verbose_name='Количество сообщений')),
                ('voice_messages_count', models.PositiveIntegerField(default=0, verbose_name='Голосовых сообщений')),
                ('commands_executed', models.PositiveIntegerField(default=0, verbose_name='Выполнено команд')),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя активность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_sessions', to='users.user')),
            ],
            options={
                'verbose_name': 'Сессия бота',
                'verbose_name_plural': 'Сессии бота',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['user', 'is_active'], name='bot_botsess_user_id_ec4568_idx'), models.Index(fields=['telegram_chat_id'], name='bot_botsess_telegra_7a25f8_idx'), models.Index(fields=['last_activity_at'], name='bot_botsess_last_ac_a1a0d0_idx')],
            },
        ),
    ]
