# Generated by Django 4.2.9 on 2025-06-24 07:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_first_name_user_last_name_user_username'),
        ('categories', '0001_initial'),
        ('transactions', '0002_debttransaction_remove_debt_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма долга')),
                ('debtor_name', models.CharField(max_length=100, verbose_name='Имя должника/кредитора')),
                ('direction', models.CharField(choices=[('from_me', 'Я дал в долг'), ('to_me', 'Мне дали в долг')], max_length=10, verbose_name='Направление долга')),
                ('date', models.DateTimeField(verbose_name='Дата создания долга')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт')], default='open', max_length=10, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Долг',
                'verbose_name_plural': 'Долги',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.RemoveField(
            model_name='debttransaction',
            name='transaction_ptr',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='transaction_user_id_dc0f22_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='related_user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='source',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='telegram_notified',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.user'),
        ),
        migrations.DeleteModel(
            name='DebtTransaction',
        ),
        migrations.AddField(
            model_name='debt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='users.user'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['user', 'status'], name='transaction_user_id_e74109_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['date'], name='transaction_date_092c76_idx'),
        ),
    ]
