# Generated by Django 4.2.9 on 2025-06-17 10:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название цели')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Целевая сумма')),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Текущая сумма')),
                ('deadline', models.DateField(verbose_name='Срок достижения цели')),
                ('reminder_interval', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='weekly', max_length=10, verbose_name='Интервал напоминаний')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Цель достигнута')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='users.user')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'is_completed'], name='goals_goal_user_id_c14f76_idx'), models.Index(fields=['deadline'], name='goals_goal_deadlin_309c22_idx')],
            },
        ),
    ]
