# Generated by Django 5.0.3 on 2025-06-17 12:09

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма пополнения')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание операции')),
                ('telegram_notified', models.BooleanField(default=False, verbose_name='Telegram уведомление отправлено')),
            ],
            options={
                'verbose_name': 'Транзакция цели',
                'verbose_name_plural': 'Транзакции целей',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveIndex(
            model_name='goal',
            name='goals_goal_user_id_c14f76_idx',
        ),
        migrations.RemoveIndex(
            model_name='goal',
            name='goals_goal_deadlin_309c22_idx',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание цели'),
        ),
        migrations.AddField(
            model_name='goal',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее напоминание отправлено'),
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('active', 'Активная'), ('completed', 'Завершена'), ('failed', 'Провалена'), ('paused', 'Приостановлена')], default='active', max_length=10, verbose_name='Статус цели'),
        ),
        migrations.AddField(
            model_name='goal',
            name='telegram_notified',
            field=models.BooleanField(default=False, verbose_name='Telegram уведомление отправлено'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='reminder_interval',
            field=models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('never', 'Никогда')], default='weekly', max_length=10, verbose_name='Интервал напоминаний'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'status'], name='goals_goal_user_id_7ad9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['deadline', 'status'], name='goals_goal_deadlin_319da5_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['status'], name='goals_goal_status_ea0ea8_idx'),
        ),
        migrations.AddField(
            model_name='goaltransaction',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='goals.goal', verbose_name='Цель'),
        ),
        migrations.AddIndex(
            model_name='goaltransaction',
            index=models.Index(fields=['goal', 'created_at'], name='goals_goalt_goal_id_e9b82d_idx'),
        ),
        migrations.AddIndex(
            model_name='goaltransaction',
            index=models.Index(fields=['created_at'], name='goals_goalt_created_046af4_idx'),
        ),
    ]
