# Generated by Django 4.2.9 on 2025-06-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goaltransaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goaltransaction',
            name='goal',
        ),
        migrations.RemoveIndex(
            model_name='goal',
            name='goals_goal_user_id_7ad9fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='goal',
            name='goals_goal_deadlin_319da5_idx',
        ),
        migrations.RemoveIndex(
            model_name='goal',
            name='goals_goal_status_ea0ea8_idx',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='last_reminder_sent',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='telegram_notified',
        ),
        migrations.AddField(
            model_name='goal',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Цель достигнута'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='reminder_interval',
            field=models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='weekly', max_length=10, verbose_name='Интервал напоминаний'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'is_completed'], name='goals_goal_user_id_c14f76_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['deadline'], name='goals_goal_deadlin_309c22_idx'),
        ),
        migrations.DeleteModel(
            name='GoalTransaction',
        ),
    ]
