# Generated by Django 4.2.9 on 2025-06-17 10:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок рассылки')),
                ('body', models.TextField(verbose_name='Текст сообщения')),
                ('send_at', models.DateTimeField(help_text='Если не указано, отправится немедленно', verbose_name='Дата отправки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланировано'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='draft', max_length=10, verbose_name='Статус')),
                ('target_audience', models.CharField(choices=[('all', 'Все пользователи'), ('active', 'Только активные'), ('inactive', 'Неактивные'), ('new', 'Новые (за последние 7 дней)'), ('custom', 'Кастомная группа')], default='active', max_length=10, verbose_name='Целевая аудитория')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Отправлено')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BroadcastUserLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('read', 'Прочитано')], default='pending', max_length=10, verbose_name='Статус отправки')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Время прочтения')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_logs', to='broadcast.broadcastmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_logs', to='users.user')),
            ],
            options={
                'verbose_name': 'Лог рассылки',
                'verbose_name_plural': 'Логи рассылок',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(fields=['status'], name='broadcast_b_status_b4b5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastmessage',
            index=models.Index(fields=['send_at'], name='broadcast_b_send_at_62ad7e_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastuserlog',
            index=models.Index(fields=['message', 'status'], name='broadcast_b_message_ea2504_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastuserlog',
            index=models.Index(fields=['user'], name='broadcast_b_user_id_7c7aad_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcastuserlog',
            index=models.Index(fields=['sent_at'], name='broadcast_b_sent_at_a333a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='broadcastuserlog',
            unique_together={('message', 'user')},
        ),
    ]
