# Generated by Django 4.2.9 on 2025-06-17 13:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_file', models.ImageField(upload_to='ocr/images/%Y/%m/', verbose_name='Изображение чека')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('raw_text', models.TextField(blank=True, verbose_name='Сырой текст OCR')),
                ('processed_text', models.TextField(blank=True, verbose_name='Обработанный текст')),
                ('confidence_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Уровень уверенности')),
                ('shop_name', models.CharField(blank=True, max_length=255, verbose_name='Название магазина')),
                ('receipt_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата чека')),
                ('receipt_number', models.CharField(blank=True, max_length=100, verbose_name='Номер чека')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Общая сумма')),
                ('status', models.CharField(choices=[('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('pending_review', 'Требует проверки')], default='processing', max_length=20, verbose_name='Статус обработки')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('processing_time', models.FloatField(default=0.0, verbose_name='Время обработки (сек)')),
                ('language_detected', models.CharField(blank=True, max_length=10, verbose_name='Определенный язык')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_results', to='users.user')),
            ],
            options={
                'verbose_name': 'Результат OCR',
                'verbose_name_plural': 'Результаты OCR',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='VoiceResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(upload_to='voice/audio/%Y/%m/', verbose_name='Аудио файл')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('duration', models.FloatField(default=0.0, verbose_name='Длительность (сек)')),
                ('recognized_text', models.TextField(blank=True, verbose_name='Распознанный текст')),
                ('confidence_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Уровень уверенности')),
                ('language_detected', models.CharField(blank=True, max_length=10, verbose_name='Определенный язык')),
                ('recognition_type', models.CharField(choices=[('expense_description', 'Описание расходов'), ('voice_command', 'Голосовая команда'), ('receipt_description', 'Описание чека'), ('general', 'Общее')], default='general', max_length=20, verbose_name='Тип распознавания')),
                ('status', models.CharField(choices=[('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='processing', max_length=20, verbose_name='Статус обработки')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('processing_time', models.FloatField(default=0.0, verbose_name='Время обработки (сек)')),
                ('model_used', models.CharField(blank=True, max_length=50, verbose_name='Использованная модель')),
                ('ocr_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_descriptions', to='ai.ocrresult', verbose_name='Связанный OCR результат')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_results', to='users.user')),
            ],
            options={
                'verbose_name': 'Результат распознавания голоса',
                'verbose_name_plural': 'Результаты распознавания голоса',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='VoiceCommand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(choices=[('create_category', 'Создать категорию'), ('add_expense', 'Добавить расход'), ('show_balance', 'Показать баланс'), ('delete_category', 'Удалить категорию'), ('manage_debt', 'Управление долгами'), ('show_stats', 'Показать статистику'), ('unknown', 'Неизвестная команда')], max_length=20, verbose_name='Тип команды')),
                ('command_text', models.TextField(verbose_name='Текст команды')),
                ('extracted_params', models.JSONField(default=dict, verbose_name='Извлеченные параметры')),
                ('execution_status', models.CharField(choices=[('pending', 'Ожидает выполнения'), ('executed', 'Выполнена'), ('failed', 'Ошибка выполнения'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус выполнения')),
                ('execution_result', models.JSONField(blank=True, default=dict, verbose_name='Результат выполнения')),
                ('execution_error', models.TextField(blank=True, verbose_name='Ошибка выполнения')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время выполнения')),
                ('confidence_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Уверенность в команде')),
                ('voice_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='command', to='ai.voiceresult', verbose_name='Результат распознавания')),
            ],
            options={
                'verbose_name': 'Голосовая команда',
                'verbose_name_plural': 'Голосовые команды',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OCRItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, verbose_name='Название товара/услуги')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена за единицу')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Общая стоимость')),
                ('category_confidence', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Уверенность в категории')),
                ('line_number', models.PositiveIntegerField(default=1, verbose_name='Номер строки')),
                ('raw_text_line', models.TextField(blank=True, verbose_name='Исходная строка текста')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category', verbose_name='Категория')),
                ('ocr_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ai.ocrresult', verbose_name='Результат OCR')),
            ],
            options={
                'verbose_name': 'Позиция чека',
                'verbose_name_plural': 'Позиции чеков',
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='AIProcessingLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('ocr_scan', 'OCR сканирование'), ('voice_recognition', 'Распознавание голоса'), ('nlp_analysis', 'NLP анализ'), ('command_execution', 'Выполнение команды'), ('category_matching', 'Сопоставление категорий')], max_length=20, verbose_name='Тип операции')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], max_length=10, verbose_name='Уровень')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('execution_time', models.FloatField(default=0.0, verbose_name='Время выполнения (сек)')),
                ('memory_used', models.FloatField(default=0.0, verbose_name='Использовано памяти (MB)')),
                ('ocr_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.ocrresult', verbose_name='OCR результат')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='users.user', verbose_name='Пользователь')),
                ('voice_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.voiceresult', verbose_name='Voice результат')),
            ],
            options={
                'verbose_name': 'Лог AI обработки',
                'verbose_name_plural': 'Логи AI обработки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='voiceresult',
            index=models.Index(fields=['user', 'status'], name='ai_voiceres_user_id_c265b0_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceresult',
            index=models.Index(fields=['recognition_type', 'status'], name='ai_voiceres_recogni_6e93ab_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceresult',
            index=models.Index(fields=['created_at'], name='ai_voiceres_created_29436f_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecommand',
            index=models.Index(fields=['command_type', 'execution_status'], name='ai_voicecom_command_ebc949_idx'),
        ),
        migrations.AddIndex(
            model_name='voicecommand',
            index=models.Index(fields=['created_at'], name='ai_voicecom_created_1cdeda_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrresult',
            index=models.Index(fields=['user', 'status'], name='ai_ocrresul_user_id_71fbe2_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrresult',
            index=models.Index(fields=['created_at', 'status'], name='ai_ocrresul_created_aeec58_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrresult',
            index=models.Index(fields=['shop_name'], name='ai_ocrresul_shop_na_ae5787_idx'),
        ),
        migrations.AddIndex(
            model_name='ocritem',
            index=models.Index(fields=['ocr_result', 'line_number'], name='ai_ocritem_ocr_res_32dfbe_idx'),
        ),
        migrations.AddIndex(
            model_name='ocritem',
            index=models.Index(fields=['category'], name='ai_ocritem_categor_4dc67d_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprocessinglog',
            index=models.Index(fields=['user', 'operation_type'], name='ai_aiproces_user_id_8838ae_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprocessinglog',
            index=models.Index(fields=['level', 'created_at'], name='ai_aiproces_level_e54a67_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprocessinglog',
            index=models.Index(fields=['operation_type', 'created_at'], name='ai_aiproces_operati_c4888b_idx'),
        ),
    ]
