# Generated by Django 5.0.3 on 2025-06-17 21:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('users', '0002_user_first_name_user_last_name_user_telegram_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptVoiceMatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Уверенность сопоставления')),
                ('voice_items', models.JSONField(blank=True, default=list, verbose_name='Товары из голоса')),
                ('total_amount_voice', models.FloatField(default=0.0, verbose_name='Общая сумма из голоса')),
                ('receipt_items', models.JSONField(blank=True, default=list, verbose_name='Товары из чека')),
                ('total_amount_receipt', models.FloatField(default=0.0, verbose_name='Общая сумма из чека')),
                ('matched_items', models.JSONField(blank=True, default=list, verbose_name='Сопоставленные товары')),
                ('matching_details', models.JSONField(blank=True, default=dict, verbose_name='Детали сопоставления')),
                ('status', models.CharField(choices=[('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='processing', max_length=20, verbose_name='Статус обработки')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('time_difference_minutes', models.IntegerField(default=0, verbose_name='Разница во времени (мин)')),
                ('ocr_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_matches', to='ai.ocrresult', verbose_name='Результат OCR чека')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_voice_matches', to='users.user', verbose_name='Пользователь')),
                ('voice_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_matches', to='ai.voiceresult', verbose_name='Результат распознавания голоса')),
            ],
            options={
                'verbose_name': 'Сопоставление голоса с чеком',
                'verbose_name_plural': 'Сопоставления голоса с чеками',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='ai_receiptv_user_id_e8f2d9_idx'), models.Index(fields=['confidence_score'], name='ai_receiptv_confide_2ebacf_idx'), models.Index(fields=['created_at'], name='ai_receiptv_created_83c615_idx'), models.Index(fields=['voice_result', 'ocr_result'], name='ai_receiptv_voice_r_5a3dc5_idx')],
                'unique_together': {('voice_result', 'ocr_result')},
            },
        ),
    ]
